SAMPLE_REQUEST = {
    "profile": {
        "income_monthly": 5200,
        "expenses_monthly": 3400,
        "savings": 12000,
        "debt": 15000,
        "industry": "Tech",
        "job_stability": "stable",
        "dependents": 0,
    },
    "scenario": {
        "months_unemployed": 6,
        "expense_cut_pct": 15,
        "severance": 3000,
        "unemployment_benefit_monthly": 800,
        "other_income_monthly": 0,
        "extra_monthly_expenses": 150,
        "debt_payment_monthly": 220,
        "healthcare_monthly": 180,
        "dependent_care_monthly": 0,
        "job_search_monthly": 75,
        "one_time_expense": 1200,
        "relocation_cost": 0,
    },
    "subscriptions": [
        {"name": "Netflix", "monthly_cost": 15.49},
        {"name": "Spotify", "monthly_cost": 10.99},
        {"name": "Gym Membership", "monthly_cost": 45.0},
    ],
    "news_event": {
        "headline": "Large tech firms announce new layoffs",
        "risk_delta": 15,
        "industry": "Tech",
    },
}
